
/** ----------------------------------------------------------------------------------------------------
* 
*	This code was automatically generated by the LeanFT Application Model code generator.
*
*	Changes to this file may cause incorrect behavior and will be lost 
*	when the code is regenerated.
*
*   ----------------------------------------------------------------------------------------------------
*/
package com.letzautomate.appmodel;

import com.hp.lft.sdk.*;

// This class is automatically generated by the LeanFT Application Model code generator - version 14.53
public class applicationName extends AppModelBase {	
	public applicationName(TestObject contextTestObject) throws GeneralLeanFtException
	{
		setName("applicationName");
				rebuildDescriptions();
	}	
}
